import type { Deps } from "./lib/deps";

// Hono type environment shared by all routes/middleware.
// `Env` (bindings) is generated by `pnpm cf-typegen` into worker-configuration.d.ts.
// ENVIRONMENT is widened to string on purpose: createDeps treats any
// unrecognized value as non-production (fakes), and the auth middleware treats
// it as production (fail closed), so the type must not pretend the value is
// always one of the configured literals.
// TELEGRAM_BOT_TOKEN is a secret (not in wrangler vars), so cf-typegen does not
// surface it — declare it optional here. Only production sets it; its absence is
// what flips createDeps to the fake Telegram client.
// TELEGRAM_WEBHOOK_SECRET is a secret in production but a fixed committed var in
// the e2e env (so the hermetic suite can drive the webhook); cf-typegen would
// otherwise narrow it to the e2e literal, so it is widened to string here. Its
// absence fails the webhook closed.
// TELEGRAM_BOT_USERNAME is widened to string for the same reason as ENVIRONMENT:
// the committed var is "" but production carries a real username, so the type
// must not pretend it is always the empty-string literal.
// GOOGLE_CLIENT_ID + GOOGLE_CLIENT_SECRET are production-only secrets (the Worker
// runs the Google OAuth flow). Optional here for the same reason as the Telegram
// secrets: local/e2e use the fake OAuth seam, so their absence is expected there.
// DIGEST_COOLDOWN_SECONDS is a committed var (0 in local/e2e, 600 in prod);
// cf-typegen narrows it to that literal union, so it is widened to number here.
// TURNSTILE_SITE_KEY + TURNSTILE_SECRET_KEY are production-only secrets installed
// by the deploy workflow (like the Telegram bot creds): optional here, and their
// joint absence simply leaves the Turnstile bot-gate off (local/e2e bypass it via
// the ENVIRONMENT gate in `verifyTurnstile`).
// OWNER_EMAIL is a committed var that differs per env (real account in prod,
// seeded test account in e2e), so it is widened to string like TELEGRAM_BOT_USERNAME.
export type Bindings = Omit<
  Env,
  | "ENVIRONMENT"
  | "TELEGRAM_BOT_USERNAME"
  | "TELEGRAM_WEBHOOK_SECRET"
  | "DIGEST_COOLDOWN_SECONDS"
  | "OWNER_EMAIL"
> & {
  ENVIRONMENT: string;
  TELEGRAM_BOT_USERNAME: string;
  OWNER_EMAIL: string;
  TELEGRAM_BOT_TOKEN?: string;
  TELEGRAM_WEBHOOK_SECRET?: string;
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  DIGEST_COOLDOWN_SECONDS: number;
  TURNSTILE_SITE_KEY?: string;
  TURNSTILE_SECRET_KEY?: string;
};

export interface AppEnv {
  Bindings: Bindings;
  Variables: {
    userEmail: string;
    deps: Deps;
  };
}
